### ISSUE TITLE
bioconda recipe no longer works

### ISSUE THREAD

**Issue by notestaff** [ngless-toolkit/ngless#101]
@luispedro The bioconda recipe for building ngless no longer seems to work:
https://circleci.com/gh/bioconda/bioconda-recipes/45506?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This may be due to upstream changes at conda-forge.  Can you see if you can make it work again?  (Background: I'm trying to make another stack-based Haskell package recipe work, and am looking for an example of a working recipe that builds with stack and works with the current conda-forge.  I don't know Haskell, unfortunately, so would be grateful for any expert help.)

**Comment by luispedro** [comment]
If I got the issue correctly, this is related to updates in the env variables that conda uses. Let's see if the CIs agree that I got the issue correctly.

**Comment by luispedro** [comment]
Bioconda now uses the _build GHC first_ approach.
