### ISSUE TITLE
Reference genomes not available Mus musculus

### ISSUE THREAD

**Issue by kunstner** [ngless-toolkit/ngless#106]
Hi,

I'm testing ngless version 1.0 (and 0.6.x) for a metagenomics project. Unfortunately, I do not manage to download the reference for Mus musculus; neither mm10.p5 nor mm10.p2 or working. I've tested two different environments (HPC and Virtual Machine) but the results are similar.

`
NGLESS=~/tmp/ngless-1.0.0/bin/ngless
$NGLESS --install-reference-data mm10.p5
[Fri 10-05-2019 10:11]: Starting download from https://ngless.embl.de/resources/References/mm10.p5.tar.gz
Exiting after fatal error while installing data
System Error
Could not connect to https://ngless.embl.de/resources/References/mm10.p5.tar.gz (got error code: 404)

`

Other references than mm10 or working (e.g. ce10).

Any advice on how to fix this problem?

Best,
 Axel

**Comment by unode** [comment]
Hi Axel,

This is an issue on our side, paths pointing to the incorrect location.
We'll fix it and let you know as soon as possible.

Sorry for the inconvenience.

**Comment by kunstner** [comment]
Hi @unode,
thanks for the fast response!
Axel

**Comment by unode** [comment]
There's also a versioning issue affecting `--install-reference-data`. Since there's no ngless script/directive it defaults to `NGLVersion 0 0` as per:
https://github.com/ngless-toolkit/ngless/blob/8bd5681a7b75c3be9ea46dae8c9b2bbf67928ae3/NGLess/NGLess/NGLEnvironment.hs#L42

I think the saner option would be to require specifying the version:
```
ngless --install-reference-data 1.0 mm10.p5
```

which would in turn allow matching the different versions. @luispedro your thoughts?

**Comment by luispedro** [comment]
The immediate issue is fixed, @kunstner please try again

The issue of no-versioning is a trickier one. Given that we have 1.0 out, we will probably not update for a bit (unlike in the run up to 1.0, where we had a release every couple of months, it seems).

**Comment by kunstner** [comment]
> The immediate issue is fixed, @kunstner please try again
> 

Thanks @luispedro for the quick fix. Seems to be working now. Best

**Comment by unode** [comment]
As the original issue is fixed I'm closing this. The issue of no versioning is now in #107 .
