### ISSUE TITLE
Output unmapped PE fastq files

### ISSUE THREAD

**Issue by ycl6** [ngless-toolkit/ngless#118]
Hi

I will like to output the unmapped reads after mapping to human genome (hg19)
Hence, after executing the following code, how can I use `write()` to output R1 and R2 fastq.gz?
```
human_mapped = map(qc_reads, reference='hg19')

non_human = select(human_mapped) using |mr|:
    mr = mr.filter(min_match_size=45, min_identity_pc=90, action={unmatch})
    if mr.flag({mapped}):
        discard

non_human_reads = as_reads(non_human)
```

Thanks

**Comment by luispedro** [comment]
The following should just work:

    write(non_human_reads, ofile="non_human.fq.gz")

It will actually generate files called `non_human.fq.pairs.1.gz`/`non_human.fq.pairs.2.gz`/`non_human.fq.singles.gz`.

For this type of question, the mailing-list (https://groups.google.com/forum/m/#!forum/ngless) is normally a better forum than Github issues.
