### ISSUE TITLE
ngless complains about igc version

### ISSUE THREAD

**Issue by ycl6** [ngless-toolkit/ngless#123]
Hi

Although the igc module has been bump to 1.0, but module.yaml (also Makefile) still says version 0.9.0, hence ngless is expecting 0.9.0 instead.

```
ngless/Modules/igc.ngm/1.0/module.yaml 
version: '0.9.0'

ngless/Modules/igc.ngm/1.0/Makefile
VERSION := 0.9
```

**Comment by luispedro** [comment]
This has been fixed. In fact, it's been fixed for >1 year, but the issue was not closed correctly.
