### ISSUE TITLE
Installation issue on Mac

### ISSUE THREAD

**Issue by dkinkj** [ngless-toolkit/ngless#125]
I have problems installing ngless with conda on a Mac (MacOS Mojave version 10.14.6)). I have updated to the latest version of conda (4.7.12) and I have installed the Bioconda channel but when I try to I get the following message:

```
$ conda install -c bioconda ngless
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ngless

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/bioconda/label/cf201901/osx-64
  - https://conda.anaconda.org/bioconda/label/cf201901/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

It seems like this package is not available for Mac computers  but only for linux is this correct?

**Comment by luispedro** [comment]
Through conda, yes, we do not have a MacOS version. I don't have easy access to a Mac OS computer to compile a version, but compiling from source should work.

**Comment by dkinkj** [comment]
I have tried to update my Xcode to 11.2 and now I get the following error, (I have stack version 1.9.3):

`$ make
stack build 
Building all executables for `NGLess' once. After a successful build of all of them, only specified executables will be rebuilt.
NGLess-1.0.1: build (lib + exe)
Preprocessing library for NGLess-1.0.1..
Building library for NGLess-1.0.1..
Preprocessing executable 'ngless' for NGLess-1.0.1..
Building executable 'ngless' for NGLess-1.0.1..
Linking .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/ngless/ngless ...
ld: can't open output file for writing: .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/ngless/ngless, errno=21
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building package NGLess-1.0.1 using:
      /Users/dkinkj/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 build lib:NGLess exe:ngless --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
make: *** [Makefile:117: ngless] Error 1`

I am not really familiar with stack, ghc etc. so any inputs on how to solve this would be greatly appreciated.

**Comment by cdanielmachado** [comment]
Hi @luispedro, I am also trying to setup `ngless` in my mac. I had similar problems as @dkinkj. I managed to overcome them by manually installing `ghc` and a few other dependencies with `brew`. However, after compiling, the makefile just leaves the compiled files hanging in the temporary folders...

```.stack-work/install/x86_64-osx/a2d03cee6ba29ec94f994317e9de13e830fb5803809117baabfdd40b8fff3611/8.6.5/bin```

If I try to move the `ngless` executable somewhere else, it still complains that the dependencies are not found. Any clues ?

**Comment by unode** [comment]
@luispedro maybe we could try to build binaries on Travis CI. They have a [MacOS platform](https://docs.travis-ci.com/user/reference/osx) for public use. It's a lot of trial and error to get right but could be a start...

Another option is AppVeyor but they don't [yet](https://help.appveyor.com/discussions/questions/34614-macos-roadmap) provide cloud resources, only [infrastructure](https://www.appveyor.com/docs/byoc/mac/).

**Comment by luispedro** [comment]
Offline, @psj1997 told me he got it to compile on Mac OS. We will try to make it into a continuous deployment script, at least for releases.

**Comment by unode** [comment]
Reviving this issue. GitHub now has its own CI implementation and they have all 3 main OSs provisioned. More info [here](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on)

**Comment by luispedro** [comment]
Over the shorter term, we might be able to get a working version of bioconda-build that works on `Mac OS X`: https://github.com/bioconda/bioconda-recipes/pull/20723

**Comment by luispedro** [comment]
Over the shorter term, we might be able to get a working version of bioconda-build that works on `Mac OS X`: https://github.com/bioconda/bioconda-recipes/pull/20723

**Comment by luispedro** [comment]
This is now available, so closing
