### ISSUE TITLE
Console throws an error while activating ngless environment

### ISSUE THREAD

**Issue by dmahajan980** [ngless-toolkit/ngless#128]
The console/terminal throws an error when the newly created conda environment _ngless_ is to be activated using the following command:
```bash
source activate ngless
```
The console throws the following error:
```bash
-bash: activate: No such file or directory
```

**Comment by luispedro** [comment]
This is a conda issue. I have just updated the README to use the more up to date `conda activate`, but, the underlying issue is your conda installation.

But, do try

`conda activate ngless`
