### ISSUE TITLE
Update Documentation: regarding the developer docs change in accordance with Ngless Version 1.1.0

### ISSUE THREAD

**Issue by nairsajjal** [ngless-toolkit/ngless#129]
NGless 1.1.0 has been introduced and the developer docs new link
 https://ngless.embl.de/whatsnew.html#version-1-1-0 must be updated into the Documentation so that developers can refer to the updated documentations to run, commit and maintain the codebase.

The current documentation is by the previous version's documentation and might somehow be misleading or confusing to developers trying to install or run the code at local machines themselves.

**Comment by nairsajjal** [comment]
If @luispedro and @unode allow I can clone the repo to my local machine and fork it to my GitHub repo and then start making changes and give a possible Pull Request.

**Comment by luispedro** [comment]
Yes, please do it as a PR. We welcome them!
