### ISSUE TITLE
Update Documentation: Add developer test details on how new developers can test .ngl scripts

### ISSUE THREAD

**Issue by nairsajjal** [ngless-toolkit/ngless#131]
The documentation can include details, as to how developers can test various scripts in /tests directory and then see the visualization of test logs and reports easily.
Also, links to Human Gut Metagenomics and Ocean Metagenomics can also help the new developers gain intuition on how to use the scripts and test results.
The changes I am suggesting are based on my interaction with @luispedro, and hence sharing this information can potentially help any future GSoC aspirant.

**Comment by nairsajjal** [comment]
I will be doing a pull request soon and adding on more changes to the documentation. If the changes deem good, the merge can be made. Cheers

**Comment by unode** [comment]
@nairsajjal Feel free to submit a pull request with said changes. We'd be happy to review them.

From what I can gather, the information at https://github.com/ngless-toolkit/ngless/blob/master/tests/README.md will be useful for you. In addition to this you can have a look at https://github.com/ngless-toolkit/ngless/blob/master/.travis.yml#L44 to understand how tests are run automatically with TravisCI.
