### ISSUE TITLE
Loading map file gmgc emapper2 annotations fails

### ISSUE THREAD

**Issue by uloeber** [ngless-toolkit/ngless#143]
Dear all,
I'm running into problems using the gmgc module. Somehow loading the mapping file fails. I downloaded the file manually and placed it in Modules/gmgc/1.0/cached as  dumpFile.cgi?i=GMGC10.emapper2.annotations.tsv.gz and soft linked it such that the file is accessible as GMGC10.emapper2.annotations.tsv.gz as well.
Anyways, I get the error:
![image](https://user-images.githubusercontent.com/4630715/104130862-5fe32c00-5373-11eb-8771-b66c0ea74d64.png)

Any ideas how to solve that? 
Thanks in Advance,
Ulrike

**Comment by luispedro** [comment]
Are you using ngless 1.2? Earlier versions will not work

**Comment by uloeber** [comment]
Dear Luis,
v 1.1 and it works until the mapping step. Thanks for the info, I will try again !
Yours,
Ulrike

**Comment by luispedro** [comment]
Yes, `v1.1` does not support loading a URL for annotatoins and tries to use it as a file (obviously failing)

**Comment by luispedro** [comment]
Newer versions of NGLess will eventually allow us to specify minimal versions for a particular module, so at least the error messages will be understandable.
