### ISSUE TITLE
 ngless-1.3.0-bwa not found

### ISSUE THREAD

**Issue by liuxianghui** [ngless-toolkit/ngless#147]
Dear Sir:
I install new version 1.3 of ngless recently using conda ( in the past, I had the 1.1 version and I removed the old one) by creating a new env. 
However, when I tried to run this. I found this error. --- semes that  ngless-1.3.0-bwa is not found??
What is wrong? Shall it be located at the same directory as ngless in conda which is /gpfs0/scratch/xianghui/software/anaconda3/envs/ngless/bin/?
Xianghui 

The following is from the log file of my job.
/gpfs0/scratch/xianghui/software/anaconda3/envs/ngless/bin/ngless
Exiting after fatal error while loading and running script
System Error (NGLess was not able to access some necessary resource)
^[[31mCannot find ngless-1.3.0-bwa on the system and this is a build without embedded dependencies.
^[[0m
NGLess v1.3.0 (C) NGLess authors
https://ngless.embl.de/

When publishing results from this script, please cite the following references:

         - Coelho, L.P., Alves, R., Monteiro, P., Huerta-Cepas, J., Freitas, A.T., and Bork, P.,
         NG-meta-profiler: fast processing of metagenomes using NGLess, a domain-specific language. in
         Microbiome 7:84 (2019). DOI: http://doi.org/10.1186/s40168-019-0684-8

         -

         - Li, H., 2013. Aligning sequence reads, clone sequences and assembly contigs with BWA-MEM. arXiv
         preprint arXiv:1303.3997.

         - MOCAT2: a metagenomic assembly, annotation and profiling framework. Kultima JR, Coelho LP, Forslund
         K, Huerta-Cepas J, Li S, Driessen M, et al. (2016) Bioinformatics (2016)
         doi:10.1093/bioinformatics/btw183

         - MOCAT: A Metagenomics Assembly and Gene Prediction Toolkit. Kultima JR, Sunagawa S, Li J, Chen W, Chen
         H, Mende DR, et al. (2012) PLoS ONE 7(10): e47656. doi:10.1371/journal.pone.0047656

      ======================================================================================
     Resource Usage on 2021-07-09 17:53:18.966942:
     JobId: 116319.pbs01                                 Project: all
     Submission Host: ln-0001.scelse.sg
     Exit Status: 1
     NCPUs Requested: 48                                 NCPUs Used: 48
     Memory Requested: None                              Memory Used: 89760kb
     Vmem Used: 1074418764kb
     CPU Time Used: 00:27:52
     Walltime requested: None                    Walltime Used: 00:27:55
     Start Time: Fri Jul  9 17:25:21 2021
     End Time: Fri Jul  9 17:53:18 2021
     Execution Nodes Used: (ca-0012:ncpus=48)
     ======================================================================================
~

**Comment by luispedro** [comment]
This is strange. Can you try running:

```bash
ngless --verbose --check-install
```

I would expect the `bwa` to be at `/gpfs0/scratch/xianghui/software/anaconda3/envs/ngless/share/ngless/bin/ngless-1.3.0-bwa`. Is there nothing there?

**Comment by liuxianghui** [comment]
I found out bwa is there but it is not set with right of execution.
Surprising!. After I chmod +x for it. Then ngless --verbose --check-install
seems to be working fine.

**Comment by luispedro** [comment]
Thanks! I will make NGLess give more information for this case
