### ISSUE TITLE
NGless v2.5 URL was not found while running it for the first time

### ISSUE THREAD

**Issue by evilvenom** [ngless-toolkit/ngless#150]
Unable to run NGless for the first time.
It says, "Could not connect to https://ngless.embl.de/resources/Modules/motus.ngm/2.5.tar.gz (got error code: 404)"

Is the file present somewhere else from where we can download it?

**Comment by unode** [comment]
See https://github.com/ngless-toolkit/ngless/issues/117 . You should use the `local` keyword as described in [the ngless-contrib motus example](https://github.com/ngless-toolkit/ngless-contrib/tree/master/motus.ngm#example).

The contrib module should download/install motus automatically from [this address](https://github.com/ngless-toolkit/ngless-contrib/blob/322977d5ec7db7a2080fc37910179c8408050445/motus.ngm/2.5/run.sh#L4).

**Comment by evilvenom** [comment]
It worked. Thanks for the help sir!
