### ISSUE TITLE
NGLess contain the adapter removel or not?

### ISSUE THREAD

**Issue by timeresistance1996** [ngless-toolkit/ngless#151]
I was use NGLess deal with the original fastq reads to abandon short and low quality reads directly. I wander if it is needed to remove the adapter with Trimmomatic before NGLess operate. Any senior advice will be appreciate.

**Comment by luispedro** [comment]
NGLess does not support adapter removal built-in. Our estimation was that this was a problem with older metagenomes, but most of the newer ones we see have had the adapter removal done by the machine and doing it a second time was not worth it.

**Comment by luispedro** [comment]
I'm closing here. Feel free to follow up on the mailing list: https://groups.google.com/forum/#!forum/ngless

**Comment by timeresistance1996** [comment]
Thanks for your answer. It helps undid my confusion. May i ask you one more question.
  I tried NGLess for the first time a week ago and got contigs very conveniently. However, I ran into a problem when I assembled single sample paired-end sequence with NGLess recently. The program ran about one night while it still come with no result.  It just stuck on running command line with no error was reported. I was completely floored after tried times to times. Do you know the possible reason?

**Comment by timeresistance1996** [comment]
Thanks！
"--trace" helps me figure out where  my program stopped，that is when assembling with megahit ：
[Thu 05-05-2022 22:21:05]: 	download base URL: https://ngless.embl.de/resources/
[Thu 05-05-2022 22:21:05]: 	global data directory: /root/anaconda3/envs/NGLess/bin/../share/ngless/data
[Thu 05-05-2022 22:21:05]: 	user directory: /root/.local/share/ngless
[Thu 05-05-2022 22:21:05]: 	user data directory: /root/.local/share/ngless/data
[Thu 05-05-2022 22:21:05]: 	temporary directory: /tmp
[Thu 05-05-2022 22:21:05]: 	keep temporary files: False
[Thu 05-05-2022 22:21:05]: 	create report: True
[Thu 05-05-2022 22:21:05]: 	report directory: assemble.ngl.output_ngless
[Thu 05-05-2022 22:21:05]: 	color setting: AutoColor
[Thu 05-05-2022 22:21:05]: 	print header: True
[Thu 05-05-2022 22:21:05]: 	subsample: False
[Thu 05-05-2022 22:21:05]: 	verbosity: Normal
...
[Thu 05-05-2022 22:57:33] Line 13: Calling megahit: /root/anaconda3/envs/NGLess/bin/../share/ngless/bin/ngless-1.3.0-megahit/megahit -1 /tmp/adjust_compression_preprocessed.1..fq5609-25609-5.gz -2 /tmp/adjust_compression_preprocessed.2..fq5609-35609-6.gz -r /tmp/adjust_compression_preprocessed.singles..fq5609-45609-7.gz -o /tmp/ngless-megahit-assembly.tmp5609/megahit-output --num-cpu-threads 1 --tmp-dir /tmp/ngless-megahit-tmpdir.tmp5609
[Thu 05-05-2022 22:57:33] Line 13: Will run process /root/anaconda3/envs/NGLess/bin/../share/ngless/bin/ngless-1.3.0-megahit/megahit -1 /tmp/adjust_compression_preprocessed.1..fq5609-25609-5.gz -2 /tmp/adjust_compression_preprocessed.2..fq5609-35609-6.gz -r /tmp/adjust_compression_preprocessed.singles..fq5609-45609-7.gz -o /tmp/ngless-megahit-assembly.tmp5609/megahit-output --num-cpu-threads 1 --tmp-dir /tmp/ngless-megahit-tmpdir.tmp5609
 
I have try to redownload or update NGLess but it won't helps.
Could it be a problem with my computer configuration?

**Comment by luispedro** [comment]
Could it be that `megahit` is simply still running? It can take a while. If you can try to increase the number of threads (only one is used right now)?

**Comment by timeresistance1996** [comment]
I used threads12 and got the result after waiting for a few hours. There is no problem. It may be that the data volume of this batch of samples is large. Thank you for your patience.
