### ISSUE TITLE
lock1 fails if provided string contains folders

### ISSUE THREAD

**Issue by unode** [ngless-toolkit/ngless#68]
```
samples = [
   "projectA/sampleA1",
   "projectB/sampleB1"
]
lock1(samples)
```

errors with:
```
[Sat 05-05-2018 17:07:20] Line 13: Interpreting [assignment]: lock1(Lookup 'samples' as NGList NGLString; __hash="d4531bdab467a3f1feb67e5ae87de081")
[Sat 05-05-2018 17:07:20] Line 13: Interpreting [executing module function: 'lock1']: NGOList [NGOString "projectA/sampleA1",NGOString "projectB/sampleB1"]
[Sat 05-05-2018 17:07:20] Line 13: Looking for a lock in ngless-locks/d4531bda. Total number of elements is 2 (not locked: 2; not finished: 2).
Exiting after internal error. If you can reproduce this issue, please run your script with the --trace flag and report a bug at http://github.com/luispedro/ngless/issues
ngless-locks/d4531bda/projectA/sampleA1.lock: lock: does not exist (No such file or directory)
```

**Comment by unode** [comment]
A simple workaround could be to replace any `/` or `\` (windows) in the string by `_`.

**Comment by unode** [comment]
@luispedro Realized one use-case of this code that got broken with the above fix.

#### file_with_full_paths.txt
```
/path/to/file1
/another/path/to/file2
```

```
samples = readlines('file_with_full_paths.txt')
sample = lock1(samples)
```

`sample` now contains `_path_to_file1` which follows the fix above makes the variable `sample` useless for users.
Do you see any problem in returning `/path/to/file1` from `lock1()` regardless of the name used for the lock?

**Comment by luispedro** [comment]
Yeah, that's how it should work.

**Comment by unode** [comment]
Fix in in place. Only missing a test-case to avoid future regressions.
Not sure how to go about testing this thought.

**Comment by luispedro** [comment]
Thanks! This should be mentioned in the `ChangeLog` and _What's New_ page for 1.0

Test could be:

    ngless "0.9"
    print(lock1(['testing/slashes\\ and spaces']))

**Comment by unode** [comment]
That last was already https://github.com/ngless-toolkit/ngless/blob/master/tests/parallel_folder_lock/lock.ngl minus the `print()`.
Now it tests this too.

**Comment by luispedro** [comment]
The idea of adding `print` is that you can test whether the result is correct by having a `output.stdout.txt` file.

**Comment by unode** [comment]
Yup: https://github.com/ngless-toolkit/ngless/commit/2eff0333f595d472a2aa0bc85bb5f39066c3626b
