### ISSUE TITLE
Ngless vs bionix comparison in faq?

### ISSUE THREAD

**Issue by kanishka-azimi** [ngless-toolkit/ngless#96]
I ran across one article discussing using bionix instead of cwl. I am curious to hear tradeoffs on that bionix approach with ngless

**Comment by luispedro** [comment]
Can you provide a link to the article that you mentioned? I confess to being unfamiliar with bionix.
-- 
Luis Pedro Coelho

**Comment by kanishka-azimi** [comment]
I am new to this domain, so I wouldn't prioritize this highly. This was the snippet I found: https://github.com/PapenfussLab/bionix/blob/master/abcbs_2018.md . I don't have the original paper link. There are a few repos implementing a bionix approach.

**Comment by kanishka-azimi** [comment]
I'll close this for now, you can reopen if you want to pursue this.

**Comment by luispedro** [comment]
The mailing-list (https://groups.google.com/forum/#!forum/ngless) may be a better forum for some sort of open discussion of the differences/similarities of ngless and other systems.
